name: Build Docker

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          REGISTRY: datawow
          REPOSITORY: postgresql-prometheus-adapter
        run: |
          echo ${{ steps.buildx.outputs.platforms }}
          docker buildx build \
            --push \
            --platform ${{ steps.buildx.outputs.platforms }} \
            -t $REGISTRY/$REPOSITORY:${GITHUB_REF##*/} .
